# more info here about TravisCI and Java projects
# http://docs.travis-ci.com/user/languages/java/

language: java
os: linux
dist: bionic

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  #- openjdk8
  #- openjdk9
  #- openjdk10
  - openjdk11
env:
  - MAVENBUILD=true GRADLEBUILD=false
  - MAVENBUILD=false GRADLEBUILD=true

before_install:
  - export JAVA_OPTS=-Xmx1g
  - export MAVEN_OPTS=-Xmx1g --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED 
before_script:
  - java -version
  - |
    if [ $MAVENBUILD == "true" ]; then
      ./mvnw --version
    fi
  - |
    if [ $GRADLEBUILD == "true" ]; then
      ./gradlew --version
    fi

install:
  - |
    if [ $MAVENBUILD == "true" ]; then
      ./mvnw clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    fi
  - |
    if [ $GRADLEBUILD == "true" ]; then
      ./gradlew clean compileJava compileTestJava
    fi

script:
  - |
    if [ $MAVENBUILD == "true" ]; then
      ./mvnw clean
      ./mvnw fmt:check
      ./mvnw pmd:check pmd:cpd-check
      ./mvnw checkstyle:check
      ./mvnw package
      ./mvnw spotbugs:check
      ./mvnw site
    fi
  - |
    if [ $GRADLEBUILD == "true" ]; then
      ./gradlew -i test assemble
    fi

after_success:
  - |
    if [ $MAVENBUILD == "true" ]; then
      ./mvnw coveralls:report
    fi
  - |
    if [ $GRADLEBUILD == "true" ]; then
      ./gradlew -i -S check
    fi