# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'
skip_tags: true
max_jobs: 1
#---------------------------------#
#    environment configuration    #
#---------------------------------#
clone_depth: 30
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
matrix:
  fast_finish: true
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
  - C:\Users\appveyor\.gradle -> build.gradle,gradle/wrapper/gradle-wrapper.properties,gradle.properties
install:
  - SET PATH=%PATH%;.
  - cmd: SET MAVEN_OPTS=-Xmx1g
  - cmd: SET JAVA_OPTS=-Xmx1g
  - cmd: gradlew --version
  - cmd: mvnw --version
  - cmd: java -version
#---------------------------------#
#       build configuration       #
#---------------------------------#
build:
  parallel: true
before_build:
  - mvnw clean -B
  - mvnw fmt:check -B
  - mvnw pmd:check pmd:cpd-check -B
  - mvnw checkstyle:check -B
build_script:
  - gradlew -i test assemble
  - mvnw package -B
after_build:
  - mvnw spotbugs:check -B
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - gradlew -i -S check
  - mvnw test verify -B
after_test:
  - mvnw site
