version: '{build}'
skip_tags: true
clone_depth: 30
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven\apache-maven-3.6.1" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://apachemirror.wuchna.com/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.6.1\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn clean install -B
test_script:
  - mvn clean install -B
cache:
  - C:\maven\apache-maven-3.6.1