# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'
skip_tags: true
#---------------------------------#
#    environment configuration    #
#---------------------------------#
clone_depth: 30
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
install:
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - ./mvnw clean package -B
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - ./mvnw clean install -B
