# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: ubuntu-latest

jobs:
- job: JDK19_Maven_Run
  displayName: 'JDK19-Maven-Run'
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Bash@3
      displayName: Install jdk19
      inputs:
        targetType: 'inline'
        script: |
          wget -q https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.deb
          sudo apt-get -qqy install ./jdk-19.0.2_linux-x64_bin.deb
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-19/bin/java 1919
          #echo "-----------------------------------------------------------------"
          #ls -al /usr/lib/jvm/jdk-19
          #/usr/lib/jvm/jdk-19/bin/java -version
          #sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-19/bin/java 1919
          #sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-19/bin/javac 1919
          #sudo update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/jdk-19/bin/jar 1919
          sudo update-alternatives --config java
          echo "-----------------------------------------------------------------"
          java -version
          echo "-----------------------------------------------------------------"
          ./mvnw -v
          echo "-----------------------------------------------------------------"
    - task: Bash@3
      displayName: Run jdk19 maven
      inputs:
        targetType: 'inline'
        script: |
          echo "-----------------------------------------------------------------"
          #./mvnw clean fmt:check pmd:check pmd:cpd-check checkstyle:check package spotbugs:check site
