# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: ubuntu-latest

jobs:
- job: JDK19_Maven_Run
  displayName: 'JDK19-Maven-Run'
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Bash@3
      displayName: Run jdk19 maven
      inputs:
        targetType: 'inline'
        script: |
          wget https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.deb
          sudo apt-get -qqy install ./jdk-19_linux-x64_bin.deb
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-19/bin/java 1919
          java -version
          echo $JAVA_HOME
          ls -al /usr/bin/java
          ls -al /usr/lib/jvm/jdk-19/bin/java
          ./mvnw -v
