trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - '*'

pr: none

strategy:
  matrix:
    'jdk11-latest':
      javaversion: 'jdk11'
    'jre11-latest':
      javaversion: 'jre11'
    'jdk17-latest':
      javaversion: 'jdk17'

variables:
  mvnversion: '3.9.3'

pool:
  vmImage: ubuntu-latest
steps:
  - task: Bash@3
    displayName: Find build version
    inputs:
      targetType: 'inline'
      script: |
        version=$(grep version pom.xml | grep -v '<?xml' | grep '<version>'|head -n 1|awk '{print $1}'| cut -d'>' -f 2 | cut -d'<' -f 1)
        echo "##vso[task.setvariable variable=buildversion]$version"
  - task: Docker@2
    displayName: Build latest image
    inputs:
      command: build
      containerRegistry: DockerHub
      dockerfile: '$(Build.SourcesDirectory)/docker/$(javaversion)/Dockerfile'
      buildContext: '$(Build.Repository.LocalPath)'
      repository: 'jibijose/httpbin'
      tags: '$(javaversion)-$(buildversion)'
      arguments: '--build-arg MVN_VERSION=$(mvnversion)'
  - task: Bash@3
    displayName: docker build info
    inputs:
      targetType: 'inline'
      script: |
        docker images
  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      containerRegistry : 'DockerHub'
      command: 'login'
  - task: Docker@2
    displayName: 'Push to Docker Hub'
    inputs:
      containerRegistry : 'DockerHub'
      command: 'push'
      repository: 'jibijose/httpbin'
      tags: '$(javaversion)-$(buildversion)'
  - task: Docker@2
    displayName: 'Logout from Docker Hub'
    inputs:
      command: 'logout'

