apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: registry.hub.docker.com/jibijose/httpbin:branch-jdk8-java-memory-down-scaling
          imagePullPolicy: Always
          name: httpbin
          ports:
            - containerPort: 8080
          env:
            - name: MAXRAMFRACTION
              value: "1"
            - name: GCTIMERATIO
              value: "2"
          resources:
            requests:
              memory: 1Gi
              cpu: 128m
            limits:
              memory: 1Gi
              cpu: 512m
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: httpbin
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbin
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50