---
swagger: "2.0"
info:
  description: "Java httpbin apis"
  version: "1.0.0"
  title: "Java httpbin apis"
  termsOfService: "https://github.com/jibijose/httpbin"
  contact:
    name: "Jibi Jose"
    url: "https://httpbin.org"
    email: "jibijose@yahoo.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.wordnik.com"
basePath: "/api"
tags:
- name: "Cpu Api"
- name: "Delay Api"
- name: "Health Api"
- name: "Memory Api"
- name: "Request Api"
- name: "Status codes Api"
schemes:
- "http"
- "https"
paths:
  /cpu/all/{percentage}/{time}:
    get:
      tags:
      - "Cpu Api"
      summary: "Cpu all processors operation"
      description: ""
      operationId: "cpuAllProcessors"
      parameters:
      - name: "percentage"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
          schema:
            type: "string"
        500:
          description: "Internal server error"
  /cpu/single/{percentage}/{time}:
    get:
      tags:
      - "Cpu Api"
      summary: "Cpu single processors operation"
      description: ""
      operationId: "cpuSingleProcessor"
      parameters:
      - name: "percentage"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
          schema:
            type: "string"
        500:
          description: "Internal server error"
  /delay/random/{unit}/range/{minTime}/{maxTime}:
    get:
      tags:
      - "Delay Api"
      summary: "Delay random range api"
      description: ""
      operationId: "delayRandomRange"
      parameters:
      - name: "unit"
        in: "path"
        required: true
        type: "string"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
        500:
          description: "Internal server error"
  /delay/random/{unit}/{time}:
    get:
      tags:
      - "Delay Api"
      summary: "Delay random api"
      description: ""
      operationId: "delayRandom"
      parameters:
      - name: "unit"
        in: "path"
        required: true
        type: "string"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
        500:
          description: "Internal server error"
  /delay/{unit}/{time}:
    get:
      tags:
      - "Delay Api"
      summary: "Delay constant api"
      description: ""
      operationId: "delayConstant"
      parameters:
      - name: "unit"
        in: "path"
        required: true
        type: "string"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
        500:
          description: "Internal server error"
  /health:
    get:
      tags:
      - "Health Api"
      summary: "Health api"
      description: ""
      operationId: "health"
      produces:
      - "text/plain"
      parameters: []
      responses:
        200:
          description: "Ok"
          schema:
            type: "string"
        500:
          description: "Internal server error"
  /memory/{bytes}/{time}:
    get:
      tags:
      - "Memory Api"
      summary: "Memory hold operation"
      description: ""
      operationId: "memoryHold"
      parameters:
      - name: "bytes"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "time"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
          schema:
            type: "string"
        500:
          description: "Internal server error"
  /request/headers:
    get:
      tags:
      - "Request Api"
      summary: "Request headers operation"
      description: ""
      operationId: "headers"
      produces:
      - "application/json"
      parameters:
      - name: "headers"
        in: "header"
        required: true
        type: "object"
      responses:
        200:
          description: "Ok"
          schema:
            type: "object"
            additionalProperties:
              type: "object"
        500:
          description: "Internal server error"
  /status/random/{codes}:
    get:
      tags:
      - "Status codes Api"
      summary: "Status random code api"
      description: ""
      operationId: "statusRandomCodes"
      parameters:
      - name: "codes"
        in: "path"
        description: "Comma separated status codes"
        required: true
        type: "string"
      responses:
        200:
          description: "Ok"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
  /status/{code}:
    get:
      tags:
      - "Status codes Api"
      summary: "Status code api"
      description: "Api to respond with the status code in uri"
      operationId: "statusCode"
      parameters:
      - name: "code"
        in: "path"
        description: "Status code of response"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Ok"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
