# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate ApiDocs

on:
  push:
    branches: [ "master", "swagger-auto" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
      fail-fast: false
      max-parallel: 2
    name: Generate ApiDocs ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - name: Checkout github.io
        uses: actions/checkout@v3
        with:
          repository: jibijose/jibijose.github.io
          path: githubio
      - name: Checking files
        run: |
          pwd
          git remote -v
          ls -al .
          ls -al githubio
          cd githubio
          git remote -v

