# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: CHECK1
      run: cat /home/runner/.m2/settings.xml
    - name: CHECK2
      run: cat /home/runner/work/httpbin/httpbin/settings.xml
    - name: CHECK3
      run: pwd
    - name: Publish to GitHub Packages Apache Maven
      run: ./mvnw -X deploy -s ./settings.xml -D'server-username=hahahaha' -D'server-password=hehehehe' -DskipTests
