# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Confirm gpg setup
      run: |
        gpg --version
        #gpg --gen-key
        #gpg --keyserver hkp://keyserver.ubuntu.com --send-keys 5A840505AA887D72BE6E86A9B1B6CDC7FBDD3ADB
        gpg --list-keys
        echo "${gpgpvtkey}" | base64 -d | gpg --batch --passphrase ${gpgpvtpass} --import
        gpg --list-keys
      env:
        gpgpvtkey: ${{ secrets.GPG_PVT_KEY }}
        gpgpvtpass: ${{ secrets.GPG_PVT_PASS }}
    - name: Publish packages to Maven
      run: ./mvnw deploy -s ./settings.xml -D'server-username=${serverusername}' -D'server-password=${serverpassword}' -D'gpg-password=${gpgpvtpass}' -DskipTests
      env:
        serverusername: ${{ secrets.OSSRH_USERNAME }}
        serverpassword: ${{ secrets.OSSRH_TOKEN }}
        gpgpvtpass: ${{ secrets.GPG_PVT_PASS }}
