# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate Site

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
      fail-fast: false
      max-parallel: 2
    name: Generate Site ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - name: Checkout github.io
        uses: actions/checkout@v3
        with:
          repository: jibijose/jibijose.github.io
          persist-credentials: false
      - name: Checkout httpbin
        uses: actions/checkout@v3
        with:
          repository: jibijose/httpbin
          path: githubhttpbin
          persist-credentials: false
      - name: Generating site
        run: |
          cd githubhttpbin
          ./mvnw clean site
          cd ..
      - name: Copying site
        run: |
          rm -rf httpbin/site/*
          cp -rf githubhttpbin/target/site/* httpbin/site/
          rm -rf githubhttpbin
      - name: Commit changes
        run: |
          git config --local user.name "${gitsitename}"
          git config --local user.email "${gitsiteemail}"
          git add httpbin/site/*
          CURRENTDATE=`date +"%Y-%m-%d %T"`
          git commit -m "auto-build-${CURRENTDATE}"
        env:
          gitsitename: ${{ secrets.GIT_SITE_NAME }}
          gitsiteemail: ${{ secrets.GIT_SITE_EMAIL }}
      - name: Push to github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_SITE_PAT }}
          repository: jibijose/jibijose.github.io